### ISSUE TITLE
Exporting Graph

### ISSUE THREAD

**Issue by Chaitanyachavan** [SpaceGroupUCL/depthmapX#25]
Hello,

I'm working on analysing the existing road network on the city of Istanbul.
I am facing problems in exporting the analysed data for diagrammatic use/vector format.
The option to export screen does export the curves as an .eps file which in turn i'm able to open in illustrator.
The problem occures when i save this illustrator file as a .dxf to be opened in rhino. 
There is loss of data, as most of the curves are broken and some are just absent.

Help is much appreciated,

Thanks and regards,
Chaitanya Chavan
MArch Candidate, Architectural Association.

**Comment by mrx3d** [comment]
Hi,

We’re also experimenting with this procedure and the  - much smaller city of Zoetermeer NL. Importing the .AI files directly in Rhino works well for us, in both Rhino 4 and 5. No in-between step through .DXF necessary. 


Groet, Danny Edwards


EDWARDS STADSONTWERP <http://www.edwards.nl/>

WG-plein 75
NL-1054 RB Amsterdam
t  +31 [0]20 6123630
f  +31 [0]84 8849 109
KVK 34139617

---

**Comment by Chaitanyachavan** [comment]
Hello,

Thank you so much for a quick response,
I tried zooming in and exporting, and as you pointed out, it does export perfectly.
However on a very large scale like the city of Istanbul, all the curves are exported as broken lines (even in illustrator)

Is there any other work around for exporting the vector data? Because the analysis took around 10 hours to process and i have some great results, but i am unable to take them out of the software space.

Thanks again,

Best,
Chai.

P.S. The results would be taken to rhino/grasshopper, for further network evaluation.

**Comment by mrx3d** [comment]
Now I think I understand what you mean …. Curves don’t exist in space syntax, which is line-of-sight based. Your curves are already broken up in DepthmapX, before doing any calculation.  That’s how it’s supposed to work. 

Danny

---

**Comment by Chaitanyachavan** [comment]
Hi Danny,

Uhm, i'm not quite sure if i can say that's the issue.
Attaching an image of the file, so i can make myself understood better.
The issue is that i do not have continuous vectors to work with.

Thanks,

Chai.

![untitled-1](https://cloud.githubusercontent.com/assets/15214734/10613850/fd4a5d8a-774e-11e5-979a-8de02defc979.jpg)

**Comment by varoudis** [comment]
Im not sure I understood the steps you are doing but:

anything analysed in dX should be simple lines. no polylines, no curves.
DXF import works better with older DXF format (used to be more simple and robust), something around 2004/2008.

Tasos

**Comment by jorgegil** [comment]
@Chaitanyachavan exporting the screen is not a good approach to ensure data integrity because it is... well, screen dependent. hence when you zoom in it works. the best is to export the map as data.
There's text formats (csv and tab) with line endpoint coordinates, and mif format for GIS, all saving the analysis results as well.
You can probably rebuild the geometry in Rhino from csv, and in the process keep the analysis results as attributes of the lines.
Alternatively you can open any of these formats in ArcGIS or QGIS very easily, and then export to DXF or another format that Rhino understands.
With screen export you retain the line colours, but these are just based on the analysis results, and in GIS you can easily reproduce these or create many other colour ranges for different metrics.

Jorge

**Comment by Chaitanyachavan** [comment]
@jorgegil thanks for the inputs.
I was able to recreate all the vectors by importing coordinates from the .csv file into grasshopper.
I could also remap the analyses values as they were catalogued in the same format.

Chai.

**Comment by varoudis** [comment]
wow, i didn't realise that you were using the screen export in order to transfer data!

Good that you solved it.
Tasos
