### ISSUE TITLE
Depthmath exercise

### ISSUE THREAD

**Issue by GregIoannina** [SpaceGroupUCL/depthmapX#325]
Hello everyone,
 i am new in Space Syntax and a complete novice in Depthmath. However, i am very glad to join your community!
i have a very starter's issue. As I follow the steps to implement the "Axial and Convex Analysis Using Depthmap" of the "Space syntax methodology", when i try to save the file(2nd step), the program crashes. i tried with several versions of Depthmap, but it keeps on crashing.
I tried to find the solution from any other topics but i couldn't and i can't figure it if its my computer's cofiguration or any additional program that needs to be installed.

Looking forward to your help.
Gregory

**Comment by orange-vertex** [comment]
Hi @GregIoannina,

Welcome to github and the community!

The only reason I can imagine this happens is because you are trying to save the file with a name that contains non-ascii (english) characters, or at a folder with non-ascii characters.
Make sure that the file name, the folder and all its parent folders are with ascii characters and let us know if it still crashes!

P
