### ISSUE TITLE
No data in .mif exported file

### ISSUE THREAD

**Issue by accamachog** [SpaceGroupUCL/depthmapX#359]
I am using the depthmapXnet-0,35 to run an spatial analysis, It is a segment map and I generated choice and integration values. However when I export the map in a .mif file and I open it in QGis I have no data in the attributes table, everything is in '0'. Do you know what I am doing wrong? I exported it with Map/Export/MapInfoFile. Here I leave the file in case you want to try. 

[PuenteAranda.zip](https://github.com/SpaceGroupUCL/depthmapX/files/4658509/PuenteAranda.zip)

**Comment by pklampros** [comment]
Hi there @accamachog,

We can't really help you with older versions as the problem might have been fixed in a newer one. Please try the latest version (currently [0.7.0](https://github.com/SpaceGroupUCL/depthmapX/releases/tag/v0.7.0)). From a quick test the new version outputs a proper .mif file.

Cheers,
Petros

**Comment by accamachog** [comment]
Hey @pklampros,

Thanks for your advise, I made the same exercise with the latest version (0.7.0) and I had the same result. When I export the file as a .mif I have no single value in the attributes table. You may wanna 
take a look at the images below. I think I am doing something wrong but I have no idea what it could be

![Depthmapx-0 7_QGISScreencapture](https://user-images.githubusercontent.com/65677068/82488807-2ee17e80-9aa6-11ea-839b-561de2c48324.jpg)
![Depthmapx-0 7_Screencapture](https://user-images.githubusercontent.com/65677068/82488808-2f7a1500-9aa6-11ea-8cf3-9e234c5b9fb3.jpg)

**Comment by pklampros** [comment]
Hi @accamachog,

Can you please attach the .mif and .mid files that are generated here?
Also, does the same happen if you save in the C:/ drive? (not in a folder, directly in C:/)

P

**Comment by accamachog** [comment]
Hey @pklampros,
It works! I saved it in the C:/ drive and now I have the attributes, I was saving before in a OneDrive folder; thank you very much.

![image](https://user-images.githubusercontent.com/65677068/82576635-8556c780-9b4f-11ea-8072-88fbc00996af.png)

Do you mind if I ask you something else? or should I make another issue?

My problem is: 
I have a GIS file (shapefile) with 5.582 segments, each segment has a code and that is the way I identify each segment. When I export the file as a .dxf file, open it in Depthmapx (0.7.0) and create a map segment it creates 11.605 segments. It almost double the original number of segments. My question is, as I need 1 choice/integration value per segment (the original segment) is there any way Depthmapx keeps the same segment number and geometry as I have in the original file? Or is there any chance it keeps an attribute, for example the code, so I can make an average based on the code if I have (and for sure I will) more than one value per original segment?.

![Original street segment map](https://user-images.githubusercontent.com/65677068/82577367-7cb2c100-9b50-11ea-9f7a-b8bf59015070.jpg)
![Segment map result](https://user-images.githubusercontent.com/65677068/82577370-7de3ee00-9b50-11ea-942f-b647810f7e06.jpg)

**Comment by pklampros** [comment]
Hey @accamachog,

Yes please, next time open a different issue because if someone has the same problem it's harder to find in an unrelated issue.

I think you have this problem because you have polylines in your drawing and when depthmap imports them it breaks them into multiple lines. If you have a CAD application try to explode them first and then import them into depthmap.

Also, a dxf does not hold attribute data, hence why depthmap doesn't have them. Try exporting your data as a .mif/.mid and importing those. That should help you keep attributes along the various conversions.

P

**Comment by accamachog** [comment]
Thank you @pklampros. You help me a lot :D
