### ISSUE TITLE
crushed curves and grid issue in organic plan shema

### ISSUE THREAD

**Issue by archbsr** [SpaceGroupUCL/depthmapX#401]
When I open the program, different grid numbers are suggested. I always choose the smallest grid system that is one-tenth of that suggested value. Does it affect the VMD value amongst the plans are compared? Namely, that are different grid value.

Another issue is that the curves in the organic plan chart look straight and wrong. Also, the system does not detect some points. Although I fill in the unselected points later, those points look different in the overall color spectrum in the system. Is this a problem and how do I fix it? I added the plan. the dark blue areas added manually.

![1](https://user-images.githubusercontent.com/71009828/104133975-05a89200-5398-11eb-88e3-e7074e3e12af.png)

**Comment by archbsr** [comment]
It's urgent.. Can you help please?? 
@pklampros @varoudis @blsemo

**Comment by pklampros** [comment]
Hi @archbsr,

I would say that Visual Mean Depth will not be affected too much by the different resolutions, unless of course you have effects like the ones you are showing there, i.e. where the filling does not pass through a specific passage.

The only curves that are not replicated in depthmapX are splines. If you use splines then depthmapX will just take the control points and make a polygon instead of re-creating the curve. Arcs should work fine.

The cell filling problem has to do with visibility. If the cells you are filling can be seen from already filled cells then those should also be filled if adjacent. However, the algorithm can be tricky in cases such as the one that you have there where the lines passing are so close to the centre of cells. You can manually fill them up, but I would check if they are part of the same graph. You can check this by looking at the Visual Node Count metric. If the manually filled cells have a different value than the rest of the cells then they don't belong to the same graph. You can also try to do Step Depth from one of them and see if the other cells are coloured. Another workaround is to just link between the two sides of the corridor which should allow the algorithm to pass through and calculate Depth correctly. Potentially the best solution is to make your cells smaller, though that means it will take longer to calculate the stuff you need.

Hope this helps!

**Comment by archbsr** [comment]
Yes it is. Thank you so much! @pklampros
